// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: entry.sql

package db

import (
	"context"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO entry (
    account_id,
    amount
) VALUES (
    $1, $2
) RETURNING entry_id, account_id, amount, created_at
`

type CreateEntryParams struct {
	AccountID int64 `json:"account_id"`
	Amount    int64 `json:"amount"`
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, createEntry, arg.AccountID, arg.Amount)
	var i Entry
	err := row.Scan(
		&i.EntryID,
		&i.AccountID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEntry = `-- name: DeleteEntry :exec
DELETE FROM entry 
WHERE entry_id = $1
`

func (q *Queries) DeleteEntry(ctx context.Context, entryID int64) error {
	_, err := q.db.ExecContext(ctx, deleteEntry, entryID)
	return err
}

const getEntry = `-- name: GetEntry :one
SELECT entry_id, account_id, amount, created_at FROM entry
WHERE entry_id = $1
`

func (q *Queries) GetEntry(ctx context.Context, entryID int64) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntry, entryID)
	var i Entry
	err := row.Scan(
		&i.EntryID,
		&i.AccountID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const listEntry = `-- name: ListEntry :many
SELECT entry_id, account_id, amount, created_at FROM entry
ORDER BY entry_id
LIMIT $1
OFFSET $2
`

type ListEntryParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListEntry(ctx context.Context, arg ListEntryParams) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, listEntry, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.EntryID,
			&i.AccountID,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEntry = `-- name: UpdateEntry :one
UPDATE entry
SET amount = $2
WHERE entry_id = $1
RETURNING entry_id, account_id, amount, created_at
`

type UpdateEntryParams struct {
	EntryID int64 `json:"entry_id"`
	Amount  int64 `json:"amount"`
}

func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, updateEntry, arg.EntryID, arg.Amount)
	var i Entry
	err := row.Scan(
		&i.EntryID,
		&i.AccountID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}
