// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Account struct {
	AccountID int64        `json:"account_id"`
	Owner     string       `json:"owner"`
	Balance   int64        `json:"balance"`
	Currency  string       `json:"currency"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Entry struct {
	EntryID   int64        `json:"entry_id"`
	AccountID int64        `json:"account_id"`
	Amount    int64        `json:"amount"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Transfer struct {
	TransferID    int64        `json:"transfer_id"`
	FromAccountID int64        `json:"from_account_id"`
	ToAccountID   int64        `json:"to_account_id"`
	Amount        int64        `json:"amount"`
	CreatedAt     sql.NullTime `json:"created_at"`
}
