// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (Account, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transfer, error)
	DeleteAccount(ctx context.Context, accountID int64) error
	DeleteEntry(ctx context.Context, entryID int64) error
	DeleteTransaction(ctx context.Context, transferID int64) error
	GetAccount(ctx context.Context, accountID int64) (Account, error)
	GetAccountForUpdate(ctx context.Context, accountID int64) (Account, error)
	GetEntry(ctx context.Context, entryID int64) (Entry, error)
	GetTransaction(ctx context.Context, transferID int64) (Transfer, error)
	ListAccount(ctx context.Context, arg ListAccountParams) ([]Account, error)
	ListEntry(ctx context.Context, arg ListEntryParams) ([]Entry, error)
	ListTransaction(ctx context.Context, arg ListTransactionParams) ([]Transfer, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateEntry(ctx context.Context, arg UpdateEntryParams) (Entry, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transfer, error)
}

var _ Querier = (*Queries)(nil)
